# Version: 0.6.0

services:
  weather-station-data-collector:
    build: .
    ports:
      - "8004:8080"
    volumes:
      - weather-station-data-collector-db:/usr/src/app/data

volumes:
  weather-station-data-collector-db:
